---
 apiVersion: v1
 kind: Service
 metadata:
   name: cache-svc
 spec:
   type: ClusterIP
   selector:
     app: cache
   ports:
    - name: cacheport
      port: 8000
      targetPort: 6379


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: cache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: cache
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: library/redis:5.0-alpine
          ports:
            - containerPort: 6379
              protocol: TCP