---
 apiVersion: v1
 kind: Service
 metadata:
   name: db-svc
 spec:
   type: ClusterIP
   selector:
     app: db
   ports:
    - name: dbport
      port: 8000
      targetPort: 5432


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: library/postgres:13-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env: 
            - name: POSTGRES_USER
              value: "saleor"
            - name: POSTGRES_PASSWORD
              value: "saleor"