apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNISmhkbVZsYm5KaGFtNXBhMkZ1ZEdnNlRrQnVhVUFoT1RrNSIKCQl9Cgl9
type: kubernetes.io/dockerconfigjson