apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  minReadySeconds: 10
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: praveenrajnikanth/workshop:shopizer
        ports:
        - containerPort: 8080
      imagePullSecrets: 
        - name: regcred


---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
  - port: 80
    targetPort: 8080